name: Gofit

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java & Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: |
          npm install
          cd android
          ./gradlew dependencies

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
